// Generates the DS bundle entry barrel for the storybook-shape sync of an APP
// repo (no library dist). Re-exports every storied component under the name its
// story directory uses, so window.ShiranamiWeb.<Name> exists and the import
// policy (lib/story-imports.mjs rule 2) shims story component imports to it.
import { build } from 'esbuild';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const WEB = join(ROOT, 'apps/web');
const COMPONENTS = join(WEB, 'src/components');
const idx = JSON.parse(readFileSync(join(ROOT, '.design-sync/sb-reference/index.json'), 'utf8'));

// title -> { story importPath } from index.json (story entries only)
const stories = Object.values(idx.entries).filter(e => e.type === 'story');
const byTitle = new Map();
for (const s of stories) {
  if (!byTitle.has(s.title)) byTitle.set(s.title, s.importPath);
}

const exts = ['.tsx', '.ts', '.jsx', '.js'];
function findSource(title, storyImport) {
  // storyImport like './src/components/shared/TrackRow/TrackRow.stories.tsx'
  const storyAbs = resolve(WEB, storyImport.replace(/^\.\//, ''));
  const dir = dirname(storyAbs);
  const name = title.split('/').pop();
  // primary: <dir>/<Name>.<ext>
  for (const e of exts) {
    const f = join(dir, name + e);
    if (existsSync(f)) return { file: f, name };
  }
  // fallback: index in dir
  for (const e of exts) {
    const f = join(dir, 'index' + e);
    if (existsSync(f)) return { file: f, name };
  }
  return { file: null, name };
}

const records = [];
for (const [title, imp] of byTitle) {
  const { file, name } = findSource(title, imp);
  records.push({ title, name, file });
}

// Detect export style per file via esbuild metafile (no evaluation).
async function exportsOf(file) {
  const r = await build({
    entryPoints: [file],
    bundle: false,
    write: false,
    metafile: true,
    logLevel: 'silent',
    loader: { '.ts': 'ts', '.tsx': 'tsx', '.js': 'jsx', '.jsx': 'jsx' },
  }).catch(() => null);
  if (!r) return [];
  const out = Object.values(r.metafile.outputs)[0];
  return out?.exports ?? [];
}

const missing = [];
const lines = [];
const dupNames = new Map();
const SRC = join(WEB, 'src');
for (const rec of records) {
  if (!rec.file) {
    missing.push(rec.title);
    continue;
  }
  const exps = await exportsOf(rec.file);
  // '@/'-aliased, extensionless specifier (resolved by tsconfigPathsPlugin)
  const spec =
    '@/' +
    relative(SRC, rec.file)
      .replace(/\\/g, '/')
      .replace(/\.(tsx|ts|jsx|js)$/, '');
  let line;
  if (exps.includes(rec.name)) line = `export { ${rec.name} } from '${spec}';`;
  else if (exps.includes('default')) line = `export { default as ${rec.name} } from '${spec}';`;
  else if (exps.length === 1) line = `export { ${exps[0]} as ${rec.name} } from '${spec}';`;
  else {
    missing.push(`${rec.title} (exports: ${exps.join(',') || 'none'})`);
    continue;
  }
  dupNames.set(rec.name, (dupNames.get(rec.name) ?? 0) + 1);
  lines.push(line);
}

// Preview provider wrapper (cfg.provider) — must be a bundle export.
lines.push(`export { DsPreviewRoot } from './ds-preview-providers';`);
dupNames.set('DsPreviewRoot', 1);

// Expose all Zustand stores on window.<GLOBAL> so story beforeEach/decorator
// seeding (redirected here via cfg.storyImports.shim) writes the SAME store
// instance the shipped components read -> data-driven previews render populated.
import { readdirSync } from 'node:fs';
const storeFiles = readdirSync(join(SRC, 'stores'))
  .filter(f => /\.ts$/.test(f) && !/\.(test|spec|d)\.ts$/.test(f))
  .map(f => f.replace(/\.ts$/, ''))
  .sort();
const storeLines = storeFiles.map(f => `export * from '@/stores/${f}';`);
console.log(`stores exposed on global: ${storeFiles.length}`);

// Shared React contexts whose identity must match between a story's decorator
// (which provides them) and the global component (which consumes them).
// Redirected to the global via cfg.storyImports.shim (same mechanism as stores).
storeLines.push(`export * from '@/components/onboarding/stepContext';`);

const dups = [...dupNames].filter(([, n]) => n > 1).map(([k]) => k);
writeFileSync(
  join(WEB, 'ds-entry.generated.ts'),
  '// AUTO-GENERATED by .design-sync/gen-entry.mjs — DS bundle barrel. Do not edit.\n' +
    lines.sort().join('\n') +
    '\n' +
    '// --- stores (exposed on window.<GLOBAL> for preview seeding) ---\n' +
    storeLines.join('\n') +
    '\n'
);

// .d.ts barrel at the default types-root (apps/web/index.d.ts) so the converter's
// exportedNames() sees all components as public value exports. Props are `any`
// (the converter's ts-morph project can't resolve this app's @/ aliases) — a
// documented app-shape tradeoff; real usage examples still come from stories.
const names = [...dupNames.keys()].sort();
writeFileSync(
  join(WEB, 'index.d.ts'),
  '// AUTO-GENERATED by .design-sync/gen-entry.mjs — DS exported-names anchor. Do not edit.\n' +
    names.map(n => `export declare const ${n}: (props: any) => any;`).join('\n') +
    '\n'
);

console.log(`components: ${records.length}`);
console.log(`barrel exports: ${lines.length}`);
console.log(`MISSING (${missing.length}):`);
for (const m of missing) console.log('  - ' + m);
console.log(`DUP NAMES (${dups.length}): ${dups.join(', ')}`);
