import { useQuery } from '@tanstack/react-query';
import { IS_ELECTRON } from '@/lib/platform';
import type { SmartMixResult } from '@shiranami/contracts';
import { useWeatherStore } from '@/stores/useWeatherStore';
import { useWeatherQuery } from '@/hooks/queries/useWeather';
import { useCurrentHour } from '@/hooks/useCurrentHour';

/** Smart mixes shift slowly (time-of-day + weather); refresh every ~15 min. */
const SMART_MIX_STALE_MS = 15 * 60 * 1000;

/**
 * Mood/activity/decade mixes generated by the main process from the renderer's
 * contextual signals (current local hour + the opted-in weather condition) and
 * the library's metadata. Degrades gracefully: when weather is off, only the
 * time-of-day + decade mixes come back; when the library is thin/untagged, the
 * list is empty.
 *
 * Keyed on the current hour + weather condition so the cache rolls forward as
 * the hour and weather change without re-fetching on every render.
 */
export function useSmartMixes() {
  const weatherEnabled = useWeatherStore(s => s.enabled);
  const weatherCoords = useWeatherStore(s => s.coords);
  const { data: weather } = useWeatherQuery(weatherEnabled, weatherCoords);

  const hour = useCurrentHour();
  const condition = weatherEnabled ? weather?.condition : undefined;

  return useQuery({
    // `null` = the main-process generation failed (distinct from `[]` = no
    // mixes apply); the view renders an honest "couldn't build mixes" notice
    // for null instead of masquerading as an empty library.
    queryKey: ['smartMixes', hour, condition ?? 'none'],
    queryFn: async (): Promise<SmartMixResult[] | null> => {
      return window.electronAPI.recommendations.smartMixes({ hour, weather: condition });
    },
    enabled: IS_ELECTRON,
    staleTime: SMART_MIX_STALE_MS,
  });
}
