// Typed contracts for Shiranami: domain types, IPC channel manifest, and
// shared API DTOs.
export * from './domain/track';
export * from './domain/lyrics';
export * from './domain/media';
export * from './domain/weather';
export * from './domain/recommendation';
export * from './domain/scrobble';
export * from './domain/smart-playlist';
export * from './domain/download-queue';
export * from './domain/dependencies';
export * from './domain/radio';
export * from './domain/playlist';
export * from './domain/folder';
export * from './ipc/channels';
export * from './ipc/debug';
export * from './ipc/metadata';
export * from './ipc/analysis';
export * from './ipc/companion';
export * from './ipc/doctor';
export * from './ipc/loudness';
export * from './ipc/waveform';
export * from './ipc/database';
export * from './ipc/error-codes';
export * from './ipc/history';
export * from './ipc/system';
export * from './ipc/storage';
export * from './ipc/preload-api';
export * from './share/dto';
