//! TypeScript binding export, and the guards that keep it honest.
//!
//! Architecture §2.5 and decision D7. The export runs inside `cargo test`, CI
//! then runs `git diff --exit-code` over the emitted directory, and
//! `pnpm verify:drift-guard` proves that gate can still fail.
//!
//! **The export path is a compile-time constant** ([`GENERATED_FILE`]), not an
//! environment variable. This is the direct lesson of nightcore issue #422,
//! where `TS_RS_EXPORT_DIR` came from a `.cargo/config.toml` that cargo resolves
//! by walking up from the *current directory* rather than from `--manifest-path`.
//! A run from the repo root left it unset, the generator wrote to a gitignored
//! default, and `git diff` over the guarded directory was clean because nothing
//! had been written there — so the drift guard passed vacuously for the entire
//! life of the project. `env!("CARGO_MANIFEST_DIR")` is baked in at compile time
//! and cannot vary with the caller's cwd.
//!
//! That constant is a *build-machine* path, which is exactly what §2.3 forbids
//! at **runtime** ("never `CARGO_MANIFEST_DIR` as a runtime path — it is a build
//! machine path; a CI-built release shipped broken over exactly this"). Nothing
//! here runs in the shipped app: [`export`] is called by a test and by the drift
//! guard, both of which run from a checkout where that path is correct by
//! construction.

use std::path::PathBuf;

use specta::Types;
use specta_typescript::Typescript;

use crate::error::ErrorPayload;
use crate::models;
use crate::notice::SystemNotice;
use crate::store::RendererStoreKey;

/// The file the type bindings are emitted to, resolved at compile time.
pub const GENERATED_FILE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../packages/contracts/src/generated/core.ts"
);

/// Banner prepended to the emitted file.
const HEADER: &str = "\
// Generated by `cargo test -p shiranami-core` (specta). DO NOT EDIT.
//
// Regenerate with:  cargo test -p shiranami-core --lib bindings
// CI diffs this file and fails on drift; `pnpm verify:drift-guard` proves that
// gate is not vacuous. See docs/v2/architecture.md §2.5.
";

/// Every type that crosses the IPC boundary.
///
/// Registering a type also registers everything it references, so the leaf enums
/// arrive with their parents. Phase 14 extends this with the command and event
/// collections; the shape of the file it emits is settled here so that phase
/// only adds rows.
pub fn types() -> Types {
    Types::default()
        // Errors and notices — the two shapes every namespace can produce.
        .register::<ErrorPayload>()
        .register::<SystemNotice>()
        // The settings key space the renderer is allowed to name.
        .register::<RendererStoreKey>()
        // Domain models, in the order `models::mod` declares them.
        .register::<models::InstallDependenciesResult>()
        .register::<models::ToolInstallResult>()
        .register::<models::DiscordRpcSettings>()
        .register::<models::DiscordRpcSettingsPatch>()
        .register::<models::DiscordMusicPresenceActivity>()
        .register::<models::DownloadQueueItem>()
        .register::<models::DownloadQueueSnapshot>()
        .register::<models::EnqueueDownloadInput>()
        .register::<models::ToolStatus>()
        .register::<models::DownloadLocation>()
        .register::<models::CachedToolStatus>()
        .register::<models::DependencyCheck>()
        .register::<models::DownloadProgress>()
        .register::<models::DependencyInstallProgress>()
        .register::<models::WatchedFolder>()
        .register::<models::RecordPlayInput>()
        .register::<models::PlayHistoryRecord>()
        .register::<models::ListeningHistoryEntry>()
        .register::<models::ListeningStatsSummary>()
        .register::<models::ListeningStatsTrack>()
        .register::<models::ListeningStatsArtist>()
        .register::<models::ListeningActivityPoint>()
        .register::<models::ListeningHourlyActivityPoint>()
        .register::<models::ListeningAlbumStat>()
        .register::<models::WeeklyInsights>()
        .register::<models::LyricsResult>()
        .register::<models::LyricLine>()
        .register::<models::PlaylistExtractResult>()
        .register::<models::SearchResult>()
        .register::<models::TrackMetadata>()
        .register::<models::Playlist>()
        .register::<models::PlaylistCreateInput>()
        .register::<models::PlaylistCreateWithTracksInput>()
        .register::<models::PlaylistUpdateInput>()
        .register::<models::RadioFavorite>()
        .register::<models::RadioStationInput>()
        .register::<models::DiscoverShelf>()
        .register::<models::LibraryShelf>()
        .register::<models::RecommendationShelves>()
        .register::<models::SimilarTrackResult>()
        .register::<models::SmartMixResult>()
        .register::<models::SmartMixSignals>()
        .register::<models::ScrobbleStatus>()
        .register::<models::ScrobbleConnectResult>()
        .register::<models::LastfmAuthStart>()
        .register::<models::SmartPlaylist>()
        .register::<models::SmartPlaylistDefinition>()
        .register::<models::SmartPlaylistRule>()
        .register::<models::DisplayTrack>()
        .register::<models::NewTrack>()
        .register::<models::Track>()
        .register::<models::TrackCreateInput>()
        .register::<models::TrackUpdateInput>()
        .register::<models::GeocodeResult>()
        .register::<models::WeatherCurrent>()
}

/// Render the type collection to TypeScript.
///
/// # Errors
///
/// Returns the exporter's error when a registered type cannot be represented —
/// a bare `i64` without a `#[specta(type = Number)]` override, say, which
/// `specta` refuses rather than silently truncating in the browser.
pub fn render() -> Result<String, specta_typescript::Error> {
    Typescript::default()
        .header(HEADER)
        .export(&types(), specta_serde::Format)
}

/// Write the bindings to [`GENERATED_FILE`].
///
/// # Errors
///
/// Returns the render error, or the I/O error from creating the directory or
/// writing the file.
pub fn export() -> Result<(), Box<dyn std::error::Error>> {
    let rendered = render()?;
    let path = PathBuf::from(GENERATED_FILE);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, rendered)?;
    Ok(())
}

/// Absolute path to a repo file, resolved from a compile-time constant.
#[cfg(test)]
pub(crate) fn repo_path(relative: &str) -> PathBuf {
    std::path::Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../.."))
        .join(relative)
        .canonicalize()
        .unwrap_or_else(|e| panic!("resolve {relative} from the repo root: {e}"))
}

/// Read a repo file to a string, for the mirror tests that compare a Rust
/// constant against the TypeScript literal it mirrors.
#[cfg(test)]
pub(crate) fn repo_file(relative: &str) -> String {
    let path = repo_path(relative);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Run the export exactly once per test binary.
    ///
    /// Tests run in parallel, so the assertions below cannot rely on a sibling
    /// test having written the file first — an ordering dependency that would
    /// pass locally and fail in CI, or vice versa, for no reason anyone could
    /// see.
    fn ensure_exported() {
        static EXPORTED: std::sync::Once = std::sync::Once::new();
        EXPORTED.call_once(|| {
            export().expect("export the TypeScript bindings");
        });
    }

    /// The export itself. This is the half of the gate that *writes*; CI runs
    /// `git diff --exit-code` afterwards, so a type changed without a
    /// regenerated file fails the build.
    #[test]
    fn export_bindings() {
        ensure_exported();
    }

    /// The nightcore #422 failure mode, pinned directly: a guard that writes
    /// somewhere other than the directory CI diffs can never fail. Asserting the
    /// constant resolves *into the guarded directory* is what makes the diff
    /// meaningful at all.
    #[test]
    fn the_export_path_lands_in_the_directory_ci_diffs() {
        ensure_exported();
        let generated = PathBuf::from(GENERATED_FILE);
        let guarded = repo_path("packages/contracts/src");

        let resolved_parent = generated
            .parent()
            .expect("the export path has a parent")
            .canonicalize()
            .expect("the generated directory exists after the export test");

        assert!(
            resolved_parent.starts_with(&guarded),
            "the export path {} escapes the guarded directory {} — this is exactly \
             how nightcore's drift guard became vacuous",
            resolved_parent.display(),
            guarded.display()
        );
        assert_eq!(
            generated.file_name().and_then(|name| name.to_str()),
            Some("core.ts")
        );
    }

    /// The emitted file must be tracked, or `git diff --exit-code` over it is
    /// permanently clean — the same vacuity by a different route. `.gitignore`
    /// is checked directly so the failure names the cause.
    #[test]
    fn the_generated_directory_is_not_git_ignored() {
        let output = std::process::Command::new("git")
            .args(["check-ignore", "-q", "--", GENERATED_FILE])
            .current_dir(repo_path("."))
            .status()
            .expect("run git check-ignore");
        assert!(
            !output.success(),
            "packages/contracts/src/generated is git-ignored, so the diff guard can never fail"
        );
    }

    /// Rendering is deterministic, or the guard fails on ordering noise instead
    /// of on drift and gets disabled by whoever is unlucky enough to hit it.
    #[test]
    fn rendering_twice_produces_identical_output() {
        assert_eq!(
            render().expect("first render"),
            render().expect("second render")
        );
    }

    /// The three properties the port promised the renderer, asserted against the
    /// emitted text rather than against the Rust types: camelCase keys, yt-dlp's
    /// snake_case survivors, and `number` where TypeScript says `number`.
    #[test]
    fn the_emitted_types_keep_the_casing_the_renderer_sees_today() {
        let ts = render().expect("render the bindings");

        assert!(ts.contains("albumArtist: string | null"));
        assert!(ts.contains("loudnessLufs: number | null"));
        assert!(ts.contains("filePath: string"));

        // yt-dlp's own keys, forwarded verbatim by v1 and still snake_case.
        assert!(
            ts.contains("webpage_url: string"),
            "SearchResult.webpage_url must keep yt-dlp's snake_case"
        );
        assert!(
            ts.contains("view_count?"),
            "SearchResult.view_count must keep yt-dlp's snake_case"
        );
        // …while the fields v1 added itself stay camelCase.
        assert!(ts.contains("matchConfidence?"));

        // A plain TypeScript `number`, not the `number | null` specta widens an
        // unannotated f64 into.
        assert!(
            ts.contains("enqueuedAt: number,"),
            "an epoch-millisecond field must export as a plain number"
        );
    }

    /// Strip JSDoc blocks and collapse whitespace.
    ///
    /// `specta` interleaves a variant's doc comment with the `|` separators, so
    /// a union reads as one line only once the comments are gone. Matching on
    /// the stripped text keeps these assertions about the *contract* rather than
    /// about how the exporter happens to lay out comments.
    fn without_comments(ts: &str) -> String {
        let mut out = String::with_capacity(ts.len());
        let mut rest = ts;
        while let Some(start) = rest.find("/**") {
            out.push_str(&rest[..start]);
            match rest[start..].find("*/") {
                Some(end) => rest = &rest[start + end + 2..],
                None => {
                    rest = "";
                    break;
                }
            }
        }
        out.push_str(rest);
        out.split_whitespace().collect::<Vec<_>>().join(" ")
    }

    /// The string unions the renderer switches over. A variant renamed here is a
    /// `switch` arm that silently stops matching there.
    #[test]
    fn the_emitted_enums_keep_their_string_literals() {
        let ts = without_comments(&render().expect("render the bindings"));

        assert!(ts.contains(
            r#"DownloadQueueStatus = "queued" | "active" | "converting" | "done" | "error" | "canceled";"#
        ));
        assert!(
            ts.contains(r#"LyricsSource = "lrclib" | "local-lrc" | "local-txt" | "embedded";"#)
        );
        assert!(ts.contains(r#"SystemNoticeSource = "discord" | "album-art";"#));
        assert!(ts.contains(r#"SystemNoticeLevel = "error" | "warn" | "info";"#));
        assert!(ts.contains(r#"SmartPlaylistMatchType = "all" | "any";"#));
        assert!(ts.contains(
            r#"WeatherCondition = "clear" | "partly_cloudy" | "cloudy" | "rain" | "snow" | "thunderstorm" | "fog" | "unknown";"#
        ));
        // The store allowlist reaches the renderer as a union of dot paths, so a
        // main-only key appearing here would be a security regression, visible
        // in the diff.
        assert!(ts.contains(r#""metadata-enrich.skippedIds""#));
        assert!(
            !ts.contains(r#""scrobble.settings""#),
            "a main-only key must never appear in the renderer-facing key union"
        );
    }

    // There is deliberately NO test here asserting "the committed file matches
    // the generator". Such a test would have to run after the export that this
    // very binary performs, so it would compare the freshly written file against
    // the generator that just wrote it and could never fail — a guard-shaped
    // thing incapable of guarding, which is the exact failure this whole module
    // exists to avoid. Staleness is caught where it is detectable: by
    // `git diff --exit-code` in CI, against the version control history that a
    // `cargo test` run cannot rewrite.
}
