//! The `tauri-specta` builder, the file it emits, and the guards on that file.
//!
//! §2.5 and decision D6: 155 channels across 24 namespaces need a typed
//! *callable* per channel, not just a type, because the Phase 15 shim has to
//! implement `window.electronAPI` over them. `ts-rs` gives types only; 155
//! hand-written `invoke` wrappers is exactly the hand-maintained list that has
//! already drifted by seven channels once in this repo.
//!
//! # Why the export moved here from `shiranami-core`
//!
//! Phase 2 emitted the model vocabulary from `shiranami-core` into
//! `packages/contracts/src/generated/core.ts`, and left a note that Phase 14
//! would extend it with the command and event collections. Extending it in place
//! is not possible: commands live in this crate, and core sits at rank 0 and
//! cannot depend on it.
//!
//! Two files was the alternative and is worse. `specta-typescript` emits a
//! definition for every type a signature references, so a `commands.ts` next to
//! `core.ts` would carry a second copy of `Track`, `Playlist` and forty others —
//! two declarations of one contract in one directory, which is the drift this
//! whole apparatus exists to prevent. So there is **one** file, `bindings.ts`,
//! emitted here, and core keeps [`shiranami_core::bindings::types`] as the
//! vocabulary this builder is fed.
//!
//! Core keeps its *content* tests too — casing, the string unions the renderer
//! switches over, the store-key allowlist — because those assert what the
//! vocabulary says. What moved is the file guards, which now live where the
//! writing does.
//!
//! # The guards, and why each one exists
//!
//! | Guard | What it stops |
//! | ----- | ------------- |
//! | export runs inside `cargo test`, CI then runs `git diff --exit-code` | a type changed without a regenerated file |
//! | [`GENERATED_FILE`] is a **compile-time constant** | nightcore #422: an env-derived path resolved against the caller's cwd, so the generator wrote somewhere the diff never looked and the guard passed vacuously for the project's entire life |
//! | [`the_export_path_lands_in_the_directory_ci_diffs`] | the same vacuity, asserted rather than assumed |
//! | [`the_generated_directory_is_not_git_ignored`] | the same vacuity by a different route — a tracked-file check, so `git diff` has something to diff |
//! | `pnpm verify:drift-guard` | that the diff can still **fail**, by perturbing a type and requiring it to |
//!
//! [`the_export_path_lands_in_the_directory_ci_diffs`]: tests::the_export_path_lands_in_the_directory_ci_diffs
//! [`the_generated_directory_is_not_git_ignored`]: tests::the_generated_directory_is_not_git_ignored
//!
//! `CARGO_MANIFEST_DIR` is a *build machine* path, which §2.3 forbids at
//! **runtime**. Nothing here runs in the shipped app: [`export`] is called by a
//! test and by the drift guard, both from a checkout where that path is correct
//! by construction.

use std::path::PathBuf;

use specta_typescript::Typescript;
use tauri_specta::{Builder, ErrorHandlingMode};

/// The file the bindings are emitted to, resolved at compile time.
pub const GENERATED_FILE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../packages/contracts/src/generated/bindings.ts"
);

/// Banner prepended to the emitted file.
const HEADER: &str = "\
// Generated by `cargo test -p shiranami-desktop` (tauri-specta). DO NOT EDIT.
//
// Regenerate with:  cargo test -p shiranami-desktop --lib bindings
// CI diffs this file and fails on drift; `pnpm verify:drift-guard` proves that
// gate is not vacuous. See docs/v2/architecture.md §2.5.
";

/// The builder: every command, every event, and core's type vocabulary.
///
/// `ErrorHandlingMode::Throw` is the load-bearing setting. The alternative,
/// `Result`, would have every generated call resolve to a `{ status, data } |
/// { status, error }` union — a different control flow from v1's `invoke`, which
/// **rejects**. §2.6 assigns the shim the job of reconstructing an
/// `IpcError`-shaped `Error` *from the rejection*, so a rejection is what the
/// generated callable has to produce, or the shim would have to unwrap a union
/// and re-throw at every one of 135 call sites.
pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(crate::commands::registry::namespace_list!(begin_gather))
        .events(crate::events::collect())
        // Core's vocabulary, registered whole rather than left to be pulled in
        // by whichever command signature happens to mention a type. Without
        // this, a model no command names yet would vanish from the bindings the
        // moment its namespace's lane had not landed — and reappear later,
        // producing diff churn that has nothing to do with drift.
        .types(&shiranami_core::bindings::types())
}

/// Write the bindings to [`GENERATED_FILE`].
///
/// # Errors
///
/// Returns the exporter's error when a registered type cannot be represented,
/// or the I/O error from creating the directory or writing the file.
pub fn export() -> Result<(), Box<dyn std::error::Error>> {
    let path = PathBuf::from(GENERATED_FILE);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    builder().export(Typescript::default().header(HEADER), &path)?;
    Ok(())
}

/// Absolute path to a repo file, resolved from a compile-time constant.
#[cfg(test)]
fn repo_path(relative: &str) -> PathBuf {
    std::path::Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../../.."))
        .join(relative)
        .canonicalize()
        .unwrap_or_else(|e| panic!("resolve {relative} from the repo root: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Run the export exactly once per test binary.
    ///
    /// Tests run in parallel, so the assertions below cannot rely on a sibling
    /// having written the file first — an ordering dependency that would pass
    /// locally and fail in CI, or vice versa, for no reason anyone could see.
    fn ensure_exported() {
        static EXPORTED: std::sync::Once = std::sync::Once::new();
        EXPORTED.call_once(|| {
            export().expect("export the TypeScript bindings");
        });
    }

    /// The half of the gate that *writes*. CI runs `git diff --exit-code`
    /// afterwards, so a command, event or type changed without a regenerated
    /// file fails the build.
    #[test]
    fn export_bindings() {
        ensure_exported();
    }

    /// The nightcore #422 failure mode, pinned directly: a guard that writes
    /// somewhere other than the directory CI diffs can never fail.
    #[test]
    fn the_export_path_lands_in_the_directory_ci_diffs() {
        ensure_exported();
        let generated = PathBuf::from(GENERATED_FILE);
        let guarded = repo_path("packages/contracts/src");

        let resolved_parent = generated
            .parent()
            .expect("the export path has a parent")
            .canonicalize()
            .expect("the generated directory exists after the export test");

        assert!(
            resolved_parent.starts_with(&guarded),
            "the export path {} escapes the guarded directory {} — this is exactly \
             how nightcore's drift guard became vacuous",
            resolved_parent.display(),
            guarded.display()
        );
        assert_eq!(
            generated.file_name().and_then(|name| name.to_str()),
            Some("bindings.ts")
        );
    }

    /// The emitted file must be tracked, or `git diff --exit-code` over it is
    /// permanently clean — the same vacuity by a different route.
    #[test]
    fn the_generated_directory_is_not_git_ignored() {
        let status = std::process::Command::new("git")
            .args(["check-ignore", "-q", "--", GENERATED_FILE])
            .current_dir(repo_path("."))
            .status()
            .expect("run git check-ignore");
        assert!(
            !status.success(),
            "packages/contracts/src/generated is git-ignored, so the diff guard \
             can never fail"
        );
    }

    /// Every command in the registry reached the emitted file, under the name
    /// the shim will call.
    ///
    /// The mechanical rename §2.5 specifies — `db:tracks:get-all` →
    /// `db_tracks_get_all` — is what the whole shim depends on, so it is checked
    /// against the *text* rather than against the Rust function names, which
    /// would only prove the exporter can read its own input.
    #[test]
    fn the_emitted_file_carries_every_command_under_its_ported_name() {
        ensure_exported();
        let ts = std::fs::read_to_string(GENERATED_FILE).expect("read the emitted bindings");

        /// The generated call names, as the shim will reach them. A named slice
        /// rather than an inline array so the assertion reads the same whether
        /// one namespace has landed or all twenty-four have.
        const PORTED_NAMES: &[&str] = &[
            "healthCheck",
            "storeGet",
            "storeSet",
            "storeDelete",
            "dbTracksGetAll",
            "dbTracksAddMany",
            "dbTracksExistsMany",
            "dbTracksUpdateMany",
            "libraryParseMetadata",
            "libraryScanFolder",
            "libraryScanFolderGrouped",
            "libraryScanCancel",
            "libraryValidateFiles",
            "metadataLookup",
            "metadataEnrichTracks",
            "metadataEnrichPreview",
            "metadataEnrichCancel",
            "metadataWriteTags",
            "storageGetUsage",
            "waveformGetPeaks",
        ];

        for command in PORTED_NAMES {
            assert!(
                ts.contains(command),
                "`{command}` is missing from the bindings — either its namespace \
                 is not in the shared registry list, or its `commands!` macro \
                 does not name it"
            );
        }
    }

    /// The emitted callable count matches what the registry states.
    ///
    /// Counted from the generated text rather than from `Commands`, which seals
    /// its contents. Every command body contains exactly one `__TAURI_INVOKE<`;
    /// the bare `__TAURI_INVOKE` in the import line has no type argument, so the
    /// angle bracket is what makes the count exact.
    #[test]
    fn the_emitted_callable_count_matches_the_registry() {
        use crate::commands::registry::{COMMAND_COUNT, NON_V1_COMMANDS, V1_INVOKE_CHANNEL_COUNT};

        ensure_exported();
        let ts = std::fs::read_to_string(GENERATED_FILE).expect("read the emitted bindings");
        let emitted = ts.matches("__TAURI_INVOKE<").count();

        assert_eq!(
            emitted, COMMAND_COUNT,
            "the emitted bindings carry {emitted} callables but the registry \
             states {COMMAND_COUNT} — a namespace in the shared list declared a \
             different number of commands than was recorded"
        );
        assert!(
            emitted <= V1_INVOKE_CHANNEL_COUNT + NON_V1_COMMANDS,
            "more callables than v1 had invoke channels; the parity checklist is \
             a ceiling as well as a floor"
        );
    }

    /// Every event reached the file under its **v1 channel string**, not under
    /// a kebab-cased struct name. An event the renderer cannot address is a
    /// feature that goes dark with no error anywhere.
    #[test]
    fn the_emitted_file_carries_every_event_under_its_v1_channel() {
        ensure_exported();
        let ts = std::fs::read_to_string(GENERATED_FILE).expect("read the emitted bindings");

        for name in crate::events::ALL_EVENT_NAMES {
            assert!(
                ts.contains(&format!("\"{name}\"")),
                "event channel `{name}` is missing from the bindings"
            );
        }
    }

    /// Errors reach the renderer as a **rejection**, not as a result union.
    ///
    /// `ErrorHandlingMode::Result` is tauri-specta's default, so this is the one
    /// setting a careless refactor of [`builder`] would silently revert — and
    /// reverting it changes the control flow at all 135 call sites the shim
    /// wraps.
    #[test]
    fn commands_reject_rather_than_returning_a_result_union() {
        ensure_exported();
        let ts = std::fs::read_to_string(GENERATED_FILE).expect("read the emitted bindings");

        assert!(
            !ts.contains("status: \"ok\""),
            "the bindings are in Result mode; §2.6 needs a rejection so the shim \
             can rebuild the IpcError shape from it"
        );
    }

    /// Strip JSDoc blocks.
    ///
    /// `specta` emits every Rust doc comment as JSDoc, so the generated file
    /// contains a great deal of *prose about* the contract alongside the
    /// contract. An assertion that does not separate the two is really an
    /// assertion about how the port is documented, which is the wrong thing to
    /// gate a build on.
    fn without_comments(ts: &str) -> String {
        let mut out = String::with_capacity(ts.len());
        let mut rest = ts;
        while let Some(start) = rest.find("/*") {
            out.push_str(&rest[..start]);
            match rest[start..].find("*/") {
                Some(end) => rest = &rest[start + end + 2..],
                None => {
                    rest = "";
                    break;
                }
            }
        }
        out.push_str(rest);
        out
    }

    /// The v1 sentinel has no place in the generated *surface* either — the same
    /// property `crate::error` pins on the payload, asserted on the artifact the
    /// renderer consumes.
    ///
    /// Comments are stripped first, deliberately: `ErrorPayload`'s own doc
    /// explains why the sentinel was deleted, and that explanation is worth
    /// keeping. What must never appear is the marker in a *value* — a generated
    /// helper that re-encodes one would give the shim a doubly-encoded message.
    #[test]
    fn the_generated_surface_never_mentions_the_v1_sentinel() {
        ensure_exported();
        let ts = std::fs::read_to_string(GENERATED_FILE).expect("read the emitted bindings");

        assert!(
            !without_comments(&ts).contains("__IPC_ERROR__"),
            "the sentinel appears outside a comment in the generated bindings"
        );
    }

    /// Core's vocabulary genuinely flows through this builder.
    ///
    /// Without `.types(&…)` the file would carry only what a landed command
    /// happens to reference, so a model would appear and disappear as lanes
    /// merged. `WatchedFolder` is the probe because no Phase 14 command names it
    /// — if it is present, registration rather than reachability put it there.
    #[test]
    fn core_models_are_registered_whole_and_not_merely_reachable() {
        ensure_exported();
        let ts = std::fs::read_to_string(GENERATED_FILE).expect("read the emitted bindings");

        assert!(
            ts.contains("WatchedFolder"),
            "no command references WatchedFolder, so its presence proves the \
             vocabulary is registered rather than pulled in by a signature"
        );
    }

    /// Rendering is deterministic, or the guard fails on ordering noise instead
    /// of on drift and gets disabled by whoever is unlucky enough to hit it.
    #[test]
    fn exporting_twice_produces_identical_output() {
        ensure_exported();
        let first = std::fs::read_to_string(GENERATED_FILE).expect("read once");
        export().expect("export again");
        let second = std::fs::read_to_string(GENERATED_FILE).expect("read twice");

        assert_eq!(first, second);
    }

    // There is deliberately NO test asserting "the committed file matches the
    // generator". It would have to run after the export this very binary
    // performs, so it would compare the freshly written file against the
    // generator that just wrote it and could never fail — a guard-shaped thing
    // incapable of guarding. Staleness is caught where it is detectable: by
    // `git diff --exit-code` in CI, against history a `cargo test` cannot
    // rewrite.
}
